# .circleci/config.yml

version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/node:14.17  # Use a Node.js version compatible with your project
    working_directory: ~/project
    steps:
      - checkout

      # Install Backend Dependencies
      - run:
          name: Install Backend Dependencies
          command: |
            cd backend
            npm install

      # Install Frontend Dependencies
      - run:
          name: Install Frontend Dependencies
          command: |
            cd frontend
            npm install

      # Run Backend Tests with Coverage
      - run:
          name: Run Backend Tests
          command: |
            cd backend
            npm run test:coverage

      # Run Frontend Tests with Coverage
      - run:
          name: Run Frontend Tests
          command: |
            cd frontend
            npm run test:coverage

      # Build Backend (if applicable)
      # Uncomment if your backend needs to be built
      # - run:
      #     name: Build Backend
      #     command: |
      #       cd backend
      #       npm run build

      # Build Frontend
      - run:
          name: Build Frontend
          command: |
            cd frontend
            npm run build

      # Run SonarCloud Analysis for Backend
      - run:
          name: SonarCloud Analysis for Backend
          command: |
            npm install -g sonar-scanner
            cd backend
            sonar-scanner \
              -Dsonar.projectKey=$SONAR_PROJECT_KEY_BACKEND \
              -Dsonar.organization=$SONAR_ORGANIZATION \
              -Dsonar.sources=. \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN \
              -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info

      # Run SonarCloud Analysis for Frontend
      - run:
          name: SonarCloud Analysis for Frontend
          command: |
            cd ../frontend
            sonar-scanner \
              -Dsonar.projectKey=$SONAR_PROJECT_KEY_FRONTEND \
              -Dsonar.organization=$SONAR_ORGANIZATION \
              -Dsonar.sources=. \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN \
              -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info

workflows:
  build_and_test:
    jobs:
      - build_and_test
